name: PR Checks
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v4
      with:
        cache: yarn
        cache-dependency-path: yarn.lock
    - run: yarn install --frozen-lockfile --prefer-offline
    - run: yarn lint --max-warnings=0