name: PR Checks
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
    - run: pnpm install --frozen-lockfile
    - run: pnpm lint --max-warnings=0